version: "3.9"
services:
  s0:
    image: "s0"
    tty: true
    cpus: 1.0
    networks:
      - my-net
  s1:
    image: "s0"
    tty: true
    cpus: 2.0
    networks:
      - my-net

networks:
  my-net:
    driver: bridge